import 'swiper/css';
// import "swiper/css/navigation";
// import "swiper/css/pagination";
import "../public/plugins/bootstrap/bootstrap.min.css"
import "../public/plugins/themefisher-font/style.css"
// import "../public/plugins/lightbox2/dist/css/lightbox.min.css"
// import "../public/plugins/slick-carousel/slick/slick.css"
// import "../public/plugins/slick-carousel/slick/slick-theme.css"
import "../public/css/style.css"

import { Inter } from "next/font/google"


const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Navigator | Responsive Multipurpose Bootstrap Nextjs Template",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}  id="body">{children}</body>
        </html>
    )
}
